# Generated by Django 4.0.1 on 2022-01-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_is_active_product_in_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_active',
            new_name='is_active',
        ),
    ]
